version: '3.3'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Map your local app/data folder to the container's internal app/data folder
      - ./app/data:/usr/src/app/app/data
    restart: always
